export const REQUEST_IPV4 = {
    ip: '8.8.8.8',
    continent: 'North America',
    continentCode: 'NA',
    country: 'United States',
    countryCode: 'US',
    countryEmoji: '🇺🇸',
    region: 'California',
    regionCode: 'CA',
    city: 'Mountain View',
    connectionAsn: 15_169,
    connectionOrg: 'Google LLC',
    connectionIsp: 'Google LLC',
    connectionDomain: 'google.com',
};

export const REQUEST_IPV4_MAP_OFF_ONLY = {
    ip: '9.9.9.9',
    continent: 'Europe',
    continentCode: 'EU',
    country: 'Switzerland',
    countryCode: 'CH',
    countryEmoji: '🇨🇭',
    region: 'Zurich',
    regionCode: 'ZH',
    city: 'Zürich',
    connectionAsn: 19_281,
    connectionOrg: 'Quad9',
    connectionIsp: 'Quad9',
    connectionDomain: 'quad9.net',
};

export const REQUEST_IPV6 = {
    ip: '2a00:dd80:40:100::',
    continent: 'Europe',
    continentCode: 'EU',
    country: 'Netherlands',
    countryCode: 'NL',
    countryEmoji: '🇳🇱',
    region: 'North Holland',
    regionCode: 'NH',
    city: 'Amsterdam',
    connectionAsn: 0,
    connectionOrg: '',
    connectionIsp: 'NetActuate Inc',
    connectionDomain: '',
};
