export const REQUEST_IPV4 = {
    ip: '8.8.8.8',
    continent: 'North America',
    continentCode: 'NA',
    country: 'United States',
    countryCode: 'US',
    countryEmoji: '🇺🇸',
    region: 'California',
    regionCode: 'CA',
    city: 'Mountain View',
    connectionAsn: 15_169,
    connectionOrg: 'Google LLC',
    connectionIsp: 'Google LLC',
    connectionDomain: 'google.com',
};

export const REQUEST_IPV4_MAP_OFF_ONLY = {
    ip: '1.1.1.1',
    continent: 'North America',
    continentCode: 'NA',
    country: 'United States',
    countryCode: 'US',
    countryEmoji: '🇺🇸',
    region: 'District of Columbia',
    regionCode: 'DC',
    city: 'Washington',
    connectionAsn: 13_335,
    connectionOrg: 'APNIC and Cloudflare DNS Resolver project',
    connectionIsp: 'Cloudflare, Inc.',
    connectionDomain: 'cloudflare.com',
};

export const REQUEST_IPV6 = {
    ip: '2a00:dd80:40:100::',
    continent: 'Europe',
    continentCode: 'EU',
    country: 'Netherlands',
    countryCode: 'NL',
    countryEmoji: '🇳🇱',
    region: 'North Holland',
    regionCode: 'NH',
    city: 'Amsterdam',
    connectionAsn: 0,
    connectionOrg: '',
    connectionIsp: 'NetActuate Inc',
    connectionDomain: '',
};
